### ISSUE TITLE
Could not install Erlang/OTP master from any hex.pm mirror

### ISSUE THREAD

**Issue by pguyot** [erlef/setup-beam#296] opened 2024-06-28 12:32 UTC
Starting today (?), master is no longer available. Restarting the run doesn't work.

See this run:
https://github.com/atomvm/AtomVM/actions/runs/9712387604/job/26807073004?pr=1220#step:3:18

```
Installing Erlang/OTP master - built on amd64/ubuntu-24.04
  aborted
  Waiting 16 seconds before trying again
  aborted
  Waiting 20 seconds before trying again
  Action install Erlang/OTP master failed for mirror https://builds.hex.pm,/ with Error: aborted
  Error: Could not install Erlang/OTP master from any hex.pm mirror
```

Action is invoked as follows:

```yaml
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir_version }}
```

In this run, it fails with `matrix.otp` and `matrix.elixir_version` being equal to master with ubuntu-24.04.
```yaml
        # master version of OTP/Elixir
        - os: "ubuntu-24.04"
          cc: "cc"
          cxx: "c++"
          otp: "master"
          elixir_version: "master"
```

**Comment by starbelly** [comment] 2024-06-28 12:40
I'm surprised `master` has been working for you, maybe github did you a favor for a while. `main` should work I believe.

**Comment by pguyot** [comment] 2024-06-28 13:09
It worked yesterday.
See: https://github.com/atomvm/AtomVM/actions/runs/9695958852/job/26759194572#step:3:20

It seems to me that `master` specification is also part of setup-beam tests:
https://github.com/erlef/setup-beam/blob/e7c76e536ef37c1d9da6a50c70d61d49e0127383/test/setup-beam.test.js#L256

AFAIK, erlang/otp main branch is called `master`

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 20:41
Lemme re-run the tests from our main branch. I believe we eventually target `erlang/otp` `master`.

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 21:01
I ran a test over at https://github.com/paulo-ferraz-oliveira/setup-beam-example/actions/runs/9718259064/job/26825721874. Is the result consistent with what you're expecting?

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 21:05
> It seems to me that master specification is also part of setup-beam tests

True, but it's just a unit test, it seems, not representative of an actual install.

I think what @starbelly meant is that Elixir, not Erlang, has no `master` branch.

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 21:13
I'ma test with Elixir `master` and Elixir `main`. If `main` passes, but not `master`, that's expected behaviour. After confirming it's not an action issue, please close it.

**Comment by pguyot** [comment] 2024-06-28 21:19
It seems to be a mirror issue as the problem happened for a while and seems to be gone. I don't know where these should be reported, but reliability of this action definitely is a problem.

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 21:26
> reliability of this action definitely is a problem.

We're good to accept pull requests to improve it. 😄 

On the other hand, I thought you'd added the mirror option to try and remove some of these obstacles, but here it seems you're using the default mirror (?)

**Comment by pguyot** [comment] 2024-06-28 21:33
> On the other hand, I thought you'd added the mirror option to try and remove some of these obstacles, but here it seems you're using the default mirror (?)

Indeed. I did create a PR to eventually use this option and also replace as many uses of this action with docker containers which seem to be more reliable for now.

I also took advantage of this conversation to move our elixir tag from master to main since this is what we meant indeed (thank you for pointing that) and master probably will no longer work. I don't know why it did work earlier this week and it no longer does, if it's a change in elixir repo or in hex.pm mirror.

**Comment by paulo-ferraz-oliveira** [comment] 2024-06-28 21:39
> if it's a change in elixir repo or in hex.pm mirror.

This, probably, @ericmj could reply better.

We're gonna close this issue for now.

We have an identified reliability issue (#260) which is the major (?) source of most issues (that the action's retry mechanism fails) but we've not had time to look at this or somebody that came forward to try and help fix...

**Closed by paulo-ferraz-oliveira** 2024-06-28 21:39 UTC
Labels: bug

**Comment by ericmj** [comment] 2024-06-29 11:12
Nothing has changed on builds.hex.pm and the elixir master build is still available but note that the last commit was from 2021. I don't know why you can no longer install it with the action, I can fetch it using curl.

**Comment by pguyot** [comment] 2024-06-29 14:09
Looking back at logs, I had more than a dozen of failures related to master, which fall into three categories:

1. I'm trying to install elixir master with OTP master, but OTP master is no longer compatible. The error is on our end and we need to use Elixir main instead. @starbelly thank you for pointing this.

This happened recently at least **six** times:

2024-06-29 13:47 UTC
https://github.com/pguyot/AtomVM/actions/runs/9724588699/job/26840961455#step:3:1

2024-06-29 06:38 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708006302/job/26835971051#step:3:59

2024-06-28 21:28 UTC
https://github.com/atomvm/AtomVM/actions/runs/9718629794/job/26826904883#step:3:1

2024-06-28 21:21 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708213724/job/26826898695#step:3:59

2024-06-28 18:33 UTC
https://github.com/atomvm/AtomVM/actions/runs/9717081476/job/26822010141#step:3:1

2024-06-28 12:26 UTC
https://github.com/atomvm/AtomVM/actions/runs/9709927629/job/26808118306#step:3:61

2. Erlang/OTP failed to install for no reason (what I described here)

This happened recently at least **once**:

2024-06-28 12:07 UTC
https://github.com/atomvm/AtomVM/actions/runs/9712387604/job/26807073004#step:3:24

3. Elixir master failed to install for no reason (same problem as described here for Erlang/OTP, but after Erlang/OTP was properly installed)

This happened recently at least **fourteen** times:

2024-06-28 09:43 UTC
https://github.com/atomvm/AtomVM/actions/runs/9709927629/job/26802253744#step:3:31

2024-06-28 09:09 UTC
https://github.com/atomvm/AtomVM/actions/runs/9709927629/job/26800400981#step:3:31

2024-06-28 08:38 UTC
https://github.com/atomvm/AtomVM/actions/runs/9709927629/job/26799589335#step:3:31

2024-06-28 07:07 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708213724/job/26796448990#step:3:31

2024-06-28 06:46 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708213724/job/26795840812#step:3:31

2024-06-28 06:27 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708213724/job/26795312841#step:3:31

2024-06-28 06:08 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708213724/job/26794662774#step:3:31

2024-06-28 05:44 UTC
https://github.com/atomvm/AtomVM/actions/runs/9708006302/job/26794096276#step:3:31

2024-06-28 00:41 UTC
https://github.com/atomvm/AtomVM/actions/runs/9705547106/job/26787815080#step:3:31

2024-06-27 23:12 UTC
https://github.com/atomvm/AtomVM/actions/runs/9704773893/job/26785640283#step:3:31

2024-06-27 22:48 UTC
https://github.com/atomvm/AtomVM/actions/runs/9704593971/job/26785111819#step:3:31

2024-06-27 21:40 UTC
https://github.com/atomvm/AtomVM/actions/runs/9703489507/job/26783040319#step:3:31

2024-06-27 21:22 UTC
https://github.com/atomvm/AtomVM/actions/runs/9703634973/job/26782209886#step:3:31

2024-06-27 21:02 UTC
https://github.com/atomvm/AtomVM/actions/runs/9703489507/job/26781758193#step:3:31

**Comment by ericmj** [comment] 2024-06-29 20:09
I think what would be helpful is if the action gives some indication why it failed. Did builds.txt fail to fetch, is the requested version missing in builds.txt, did the elixir/erlang zip/tar fail to fetch, etc.

**Comment by starbelly** [comment] 2024-07-03 21:36
> I think what would be helpful is if the action gives some indication why it failed. Did builds.txt fail to fetch, is the requested version missing in builds.txt, did the elixir/erlang zip/tar fail to fetch, etc.

Agreed. There's a lot of simple changes that can be done to make produce diagnostics information.

**Comment by keynslug** [comment] 2024-12-19 20:42
Sharing a data point and a couple of observations.

Builds in `eetcd` repo are [failing quite consistently](https://github.com/keynslug/eetcd/actions/runs/12419972060/job/34677595768) for me today (3 out of 3 failed attempts).

This is what I believe `setup-beam` is trying to pull from builds.hex.pm.
```
maint-27 911502609301fc5654977f2de829c7769098a95c 2024-12-17T08:59:55Z
```

This is the action output.
```
> Installing Erlang/OTP maint-27 - built on amd64/ubuntu-22.04
  aborted
  Waiting 19 seconds before trying again
  aborted
  Waiting 16 seconds before trying again
  Action install Erlang/OTP maint-27 failed for mirror https://builds.hex.pm,/ with Error: aborted
  Error: Could not install Erlang/OTP maint-27 from any hex.pm mirror
```

And the most surprising observation is how `wget` behaves for me locally.
```
--2024-12-19 21:24:00--  https://builds.hex.pm/builds/otp/amd64/ubuntu-22.04/maint-27.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving builds.hex.pm (builds.hex.pm)... 151.101.85.91
Connecting to builds.hex.pm (builds.hex.pm)|151.101.85.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72873907 (69M) [application/x-tar]
Saving to: ‘maint-27.tar.gz’

maint-27.tar.gz                                     99%[=================...================> ]  69.00M  8.03MB/s    in 8.2s

2024-12-19 21:24:08 (8.45 MB/s) - Connection closed at byte 72351744. Retrying.

--2024-12-19 21:24:09--  (try: 2)  https://builds.hex.pm/builds/otp/amd64/ubuntu-22.04/maint-27.tar.gz
Connecting to builds.hex.pm (builds.hex.pm)|151.101.85.91|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 72858633 (69M), 506889 (495K) remaining [application/x-tar]
Saving to: ‘maint-27.tar.gz’

maint-27.tar.gz                                    100%[+++++++++++++++++...+++++++++++++++>]  69.48M  --.-KB/s    in 0.06s

2024-12-19 21:24:09 (8.36 MB/s) - ‘maint-27.tar.gz’ saved [72858633/72858633]
```

Even more puzzling is the fact that the remote server always drops connection once 72351744 bytes (64 * 2^20) are transferred, regardless of download speed.

**Comment by ericmj** [comment] 2024-12-19 21:15
I cannot reproduce this, using wget it downloads successfully on the first try.

Can you go to https://www.fastly-debug.com/ and save the base64 text block and post it here or email to support@hex.pm (it contains some PII such as IP and rough location).

**Comment by wojtekmach** [comment] 2024-12-19 21:21
Id guess this is similar to https://github.com/hexpm/bob/issues/197

**Comment by keynslug** [comment] 2024-12-20 14:29
@ericmj 

Sure!

<details>
<summary>fastly-debug base64</summary>

```
ewogICJnZW9pcCI6IHsKICAgICJjaSI6ICJlbnNrZWRlIGdhcmQiLAogICAgInN0IjogIkFCIiwKICAgICJjdCI6ICJzd2VkZW4iLAogICAgImNvIjogIkVVIiwKICAgICJjX2lwIjogIjYyLjYzLjI0Ni4xMzYiLAogICAgImNfYXNuIjogIjg0NzMiLAogICAgImNfYXNuX25hbWUiOiAiYmFobmhvZiBhYiIsCiAgICAicl9pcCI6ICI3OS4xMzYuMTE5LjYiLAogICAgInJfYXNuIjogIjg0NzMiLAogICAgInJfYXNuX25hbWUiOiAiYmFobmhvZiBhYiIsCiAgICAicl9jaSI6ICJnb3RlYm9yZyIsCiAgICAicl9zdCI6ICJPIiwKICAgICJyX2N0IjogInN3ZWRlbiIsCiAgICAicl9jbyI6ICJFVSIKICB9LAogICJwb3BMYXRlbmN5IjogewogICAgImFtcyI6IDI1LAogICAgImJtYSI6IDMsCiAgICAiYnJ1IjogMjksCiAgICAiY3BoIjogMTMsCiAgICAiZHViIjogNDQsCiAgICAiZWRkZiI6IDI2LAogICAgImVnbGMiOiAzNCwKICAgICJlZ2xsIjogMzUsCiAgICAiZXRvdSI6IDMxLAogICAgImZjbyI6IDUyLAogICAgImhlbCI6IDEwLAogICAgImxmcGIiOiAzMywKICAgICJsZnBnIjogMzYsCiAgICAibGluIjogMzUsCiAgICAibGlzIjogNjIsCiAgICAibG9uIjogMzUsCiAgICAibWFkIjogNTQsCiAgICAibWFuIjogNDIsCiAgICAibXJzIjogNDQsCiAgICAibXVjIjogMjksCiAgICAibXhwIjogNDAsCiAgICAib3NsIjogMTMsCiAgICAicG1vIjogNjEsCiAgICAic29mIjogNTMsCiAgICAidmllIjogMzgsCiAgICAiYW55IjogMwogIH0sCiAgInBvcEFzc2lnbm1lbnRzIjogewogICAgImFjIjogImJtYSIsCiAgICAiYXMiOiAiYm1hIgogIH0sCiAgInJlcXVlc3QiOiB7CiAgICAicmVzb2x2ZXJfaXAiOiAiNzkuMTM2Ljk4LjI0NiIsCiAgICAicmVzb2x2ZXJfYXNfbmFtZSI6ICJCQUhOSE9GLCBTRSIsCiAgICAicmVzb2x2ZXJfYXNfbnVtYmVyIjogIjg0NzMiLAogICAgInJlc29sdmVyX2NvdW50cnlfY29kZSI6ICJTRSIsCiAgICAiY2xpZW50X2lwIjogIjYyLjYzLjI0Ni4xMzYiLAogICAgImNsaWVudF9hc19uYW1lIjogIkJBSE5IT0YsIFNFIiwKICAgICJjbGllbnRfYXNfbnVtYmVyIjogIjg0NzMiLAogICAgInRpbWUiOiAiMjAyNC0xMi0yMFQxNDoxOTo0Mi4wMDBaIiwKICAgICJob3N0IjogInd3dy5mYXN0bHktZGVidWcuY29tIiwKICAgICJhY2NlcHQiOiAidGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksKi8qO3E9MC44IiwKICAgICJ1c2VyYWdlbnQiOiAiTW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMzMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMzMuMCIsCiAgICAiYWNjZXB0bGFuZ3VhZ2UiOiAiZW4tVVMsZW47cT0wLjUiLAogICAgImFjY2VwdGVuY29kaW5nIjogImd6aXAiLAogICAgImZhc3RseXNlcnZlcmlwIjogIjE1MS4xMDEuODQuNjQiLAogICAgInhmZiI6ICI2Mi42My4yNDYuMTM2IiwKICAgICJkYXRhY2VudGVyIjogIkJNQSIsCiAgICAiYmFuZHdpZHRoX21icHMiOiAiNTIuNzkiLAogICAgImN3bmQiOiAzMjUsCiAgICAibmV4dGhvcCI6ICIxNzIuMjIuMzIuMSIsCiAgICAicnR0IjogMjQuMjg0LAogICAgIm1pbl9ydHQiOiAyLjM4MSwKICAgICJkZWx0YV9yZXRyYW5zIjogMCwKICAgICJ0b3RhbF9yZXRyYW5zIjogMAogIH0KfQ==
```

</details>

Confirming that today (2024-12-20 15:27:59 CET) it also worked cleanly on the first try for me.
