### ISSUE TITLE
Elixir installation on OTP26 hangs on Windows

### ISSUE THREAD

**Issue by mkuratczyk** [erlef/setup-beam#189] opened 2023-04-28 07:51 UTC
I realize OTP26 is not mentioned on the compatibility list but with the 26.0 coming soon, I'd love to run our CI against it. Unfortunately, when we try to use `setup-beam` with OTP26 on Windows, it just hangs trying to install / run Elixir:

<img width="958" alt="Screenshot 2023-04-28 at 09 12 04" src="https://user-images.githubusercontent.com/9566114/235079584-8c73c3af-2604-4d08-bc14-69bae240611b.png">

It gets cancelled because of a 2 hour timeout. Do you have any idea why that could be? Perhaps this has something to do with the need to use `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned` (the worker is waiting for someone to approve running the downloaded script/binary)? If so, why would 26 behave differently than 25?

Full action output including the workflow file can be found here (there is no additional detail though, even with `ACTIONS_RUNNER_DEBUG=true`):
https://github.com/rabbitmq/rabbitmq-server/actions/runs/4826327568

Thanks a lot!

**Comment by paulo-ferraz-oliveira** [comment] 2023-04-28 16:53
Hey.

Thank for the feedback.

> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

I remember some signature-related stuff changing recently, but don't know which versions it affects: https://github.com/erlang/otp/issues/7002 and https://github.com/erlang/otp/issues/6885 (might be more).

I'll push a draft pull request to check if we can have this working for OTP 26.

**Comment by paulo-ferraz-oliveira** [comment] 2023-04-28 17:54
I've been updating the pull request, but still have no concrete idea on why this is failing.

OTP 26 installs, Elixir doesn't run: those are your issue's symptoms, right?

**Comment by mkuratczyk** [comment] 2023-04-28 18:31
Exactly. It looks like OTP is downloaded and executed fine (version gets printed) but Elixir is only downloaded but then can't be executed (it hangs when it should print the version).

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-01 13:59
I have no idea what might be causing this. I have a Windows machine, but I'm away from it and with no remote access to it either.

@starbelly, @ericmj, thoughts?

**Comment by starbelly** [comment] 2023-05-01 22:54
@paulo-ferraz-oliveira No immediate thoughts on my end. I wonder if this is related to ongoing work in elixir with support for the new shell on OTP 26. I'd be curious to see what happens if this work flow was used with elixir main vs 1.14, without having access to a windows machine that would be my first stab at figuring out what's going on here. 

@mkuratczyk Have you tried running this manually on a windows machine?

**Comment by mkuratczyk** [comment] 2023-05-02 07:04
Yes, I've run `install-otp.ps1` and `install-elixir.ps1` with some minor tweaks for paths and both were downloaded and executed (printed the version). The only suspicious bit was the popup asking whether I was sure I wanted to execute something downloaded from the Internet. That's why I suspect permissions can be the reason it doesn't work (but I don't know why OTP26 would behave differently than 25). We've only tried with Elixir 1.14.4.

Note: I have zero Windows experience, but can access a machine to try things.

**Comment by lukebakken** [comment] 2023-05-02 13:25
> The only suspicious bit was the popup asking whether I was sure I wanted to execute something downloaded from the Internet

* Was this when you executed a `.ps1` file or when a downloaded `.exe` was run?
* Can you get a screenshot of the popup, or provide the exact wording?

**Comment by lukebakken** [comment] 2023-05-02 14:38
I manually ran the OTP and Elixir installation steps using [this Win 11 vagrant box](https://app.vagrantup.com/gusztavvargadr/boxes/windows-11/), and did not see any popups.

What I did see, however, was this message:

```
Line |
   4 |  & "${DIR_FOR_BIN}/bin/elixir" "-v" | Write-Output
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot run a document in the middle of a pipeline: C:\elixir\bin\elixir.
```

I'll open a PR to explicitly use the `.bat` extension in that line.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-07 01:27
> elixir main vs 1.14

@starbelly, I tested this. Same results!

**Comment by starbelly** [comment] 2023-05-07 16:52
> @starbelly, I tested this. Same results!

I think the issue (without having tested anything myself) is going to be OTP not elixir. Per the issue you referenced, there's no automagic digital signing of binaries in place. It stands to reason that OTP-26 rc releases may not (probably not) digitally signed. The installer probably is, but not the binaries are used. This would explain why OTP 25 works fine, but OTP 26 rc* does not. 

@paulo-ferraz-oliveira  Did you get the popup and if so did it tell you what executable it was unhappy with?

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-08 08:28
I didn't get a pop-up (haven't tried this out except on CI). Erlang/OTP installs just fine, and when we invoke it to get the version we do get it. Elixir hangs after we try to get it to output the installed version.

**Comment by lukebakken** [comment] 2023-05-08 12:49
@starbelly some discussion about exe signing:
* https://github.com/erlang/otp/issues/6885
* https://github.com/erlang/otp/issues/7002

@KennethL - are executables signed for RC builds?

**Comment by KennethL** [comment] 2023-05-08 15:21
All executables (on Windows) including the installer are signed. (Except the uninstaller). I think this was added in OTP 26 RC-3, before that it was only the installer that was signed.

**Comment by starbelly** [comment] 2023-05-09 00:43
> @starbelly, do you think we should involve somebody from Elixir Core?

Indeed.

**Comment by josevalim** [comment] 2023-05-09 07:18
Can you try installing Elixir v1.14.3 with OTP 26? If earlier Elixir versions work or fail, it may help pinpoint the root cause.

**Comment by mkuratczyk** [comment] 2023-05-09 09:31
I've just tried and it seems like the same problem is there with 1.14.3 (I only waited 2 minutes, but how long can it take to print the version? ;) ):
![Screenshot 2023-05-09 at 11 31 05](https://user-images.githubusercontent.com/9566114/237055588-0424df41-f7a8-4237-999b-58e5df501b74.png)

Full output: https://github.com/rabbitmq/rabbitmq-server/actions/runs/4924571907/jobs/8797756382

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-09 10:09
@josevalim, complementing what @mkuratczyk wrote... In CI I also tested with a bunch of versions, starting with 1.13.0, and couldn't find one where it worked. I also didn't wait more than a few minutes at each try.

**Comment by josevalim** [comment] 2023-05-09 10:23
FWIW, I was able to install Erlang/OTP 26-rc3 with Elixir v1.14.4 (compiled for Erlang/OTP 25) and run both elixir.bat and iex.bat:

<img width="1216" alt="Screenshot 2023-05-09 at 12 22 23" src="https://github.com/erlef/setup-beam/assets/9582/a26936a6-1f53-46dd-83ca-3473f29f8f6c">

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-09 12:56
Hm... @josevalim, shall we start suspecting the Windows image provided from GitHub? Is there any kind of change we can do to provide more info. for further debug?

**Comment by josevalim** [comment] 2023-05-09 13:29
I used a Windows 10 Virtual Box image provided by MS.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-09 19:44
With `windows-2019` I get the same results.

With Elixir over OTP 26 (build with 25) it seems to get stuck in `mix.bat`: https://github.com/erlef/setup-beam/actions/runs/4929782540/jobs/8809930402#step:3:33

**Comment by starbelly** [comment] 2023-05-10 03:53
Still no clue what's going on with this, but some progress. Stepping away from elixir and batch files, I asked myself : "Can I do anything with erl itself?" ... the answer was sort of. 

-  I can run `erl -init_debug` and get some debug
-  I can not run `erl -init_debug -s erlang halt` and it halts 
    - nor can I run different combos with `-noshell` (as should be the case with elixir) , `-eval ...`, etc.
    
 Here is a run running with just `-init_debug` : https://github.com/starbelly/test-setup-elixir/actions/runs/4932546637/jobs/8816250005
 
 And here is a run with trying to run `-init_debug -s halt` : https://github.com/starbelly/test-setup-elixir/actions/runs/4932546637/jobs/8816222809
 
 I can also pass `-init_debug` as an erl option to elixir and that works, but of course nothing after the point. 
 
So I think we can at least say, whatever the problem is exactly, I don't think it has anything to do with elixir.  Also, I'm doubtful there's a popup problem happening here, though still possible. I'm not sure what the behaviour on windows is exactly, but I would expect to see nothing in the console (e.g., erl version, init debug, etc) until an "Okay" is given by the user to continue. Of course, it could be firewall related, similar to mac os, where by once erlang tries to make a tcp connection you get a pop up and you must approve to make progress in the terminal.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-10 06:33
OTP's own GitHub workflows use `erl -noshell` [on macOS](https://github.com/erlang/otp/blob/master/.github/workflows/main.yaml#L176), but not Windows, it seems 🤔.

**Comment by starbelly** [comment] 2023-05-10 16:09
> OTP's own GitHub workflows use `erl -noshell` [on macOS](https://github.com/erlang/otp/blob/master/.github/workflows/main.yaml#L176), but not Windows, it seems 🤔.

Well, there's no testing of erl.exe itself in that workflow, unless my eyes are failing me, just a build, and on WSL. 

I got access to a windows 2022 server, I'll see if I can replicate later this evening.

**Comment by starbelly** [comment] 2023-05-10 23:58
Tried various activities on Windows 2022 server, no luck in reproducing. Everything worked perfectly, zero hiccups or warnings.

 I think, on my end and without having access to the image for github (I checked, they don't offer this for download), I can only conclude the following : 

1. It something particular with new erl shell on windows that doesn't agree with github's runner and the way we interact it with. Maybe there's a way to fiddle with those settings. One thing that stands out to me is that through any of those manual testing are we starting up erl the way it is started by the runner (see Paulos debug run above). 

2. There's something about the new erl shell that doesn't agree with how we're calling it in the action, in this case it would be how we're calling elixir.bat, which in turn calls erl.exe. Of course, per my testing last night, I couldn't get erl to behave either. 

3. There's something super funky with IO and the new shell when it comes to github's runner. This is related to 1., but a little more specific, and a big leap that I don't like either. 

4. There is something specific about the images github provides for their hosted runners, hitting some odd  security / firewall / <insert big leap here> case that is specific to OTP 26

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-11 06:46
FYI, [this](https://github.com/erlef/setup-beam/actions/runs/4930679335/jobs/8811881992#step:3:23) is the command the runner issues for JavaScript `exec`:

```
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\elixir\1.14.4\x64\bin\elixir.bat -v"
```

**Comment by lukebakken** [comment] 2023-05-11 15:07
This is a real shot in the dark, but I wonder if this could be a code page issue. Could a call to `chcp` be added [here](https://github.com/erlef/setup-beam/blob/main/src/installer.js#L109-L110) just to see what the value is?

Testing on my local Win 11 system, I see the value `65001` when I'm using powershell core / windows terminal, and `437` if I start `cmd.exe` directly. Of course I haven't been able to repro this issue either.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-11 16:11
I can add that to my pull request for testing, sure. Thanks @lukebakken. Will link here after I have some results.

**Comment by lukebakken** [comment] 2023-05-11 16:18
I was just looking for a weird value. 65001 is UTF-8 so there shouldn't be an issue. So much for that idea!

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-11 16:21
Wouldn't it be nice if it worked with `437` 😄 We'd need to go down another rabbit hole hahaha... spoiler alert: it doesn't 😆

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-17 11:09
> Erlang/OTP 26-rc3 with Elixir v1.14.4 (compiled for Erlang/OTP 25)

This was not possible until recently, but while investigating this bug I made it possible, when using `version-type` `strict`: https://github.com/erlef/setup-beam/pull/191/files#diff-6406ae11684199b17d2cdca1efe2cfa29fb4587c3b142f1d33ad5f81a5acf7adR188

Still, Erlang/OTP 26.0 + Elixir 1.14 (build fetched from Hex) shows the same issue on Windows.

**Comment by starbelly** [comment] 2023-05-17 22:33
I wonder if we can / should reach out to github. One of the issues here is we have no visibility into what's happening. I mean, maybe there's some windows debug fu we can do that I'm not aware of.

**Comment by starbelly** [comment] 2023-05-18 00:05
Ok, so I came back again and said hmm : "Is seems like arguments aren't making it to erl properly or parsed weird for some reason"... and that some what seems to be the case. 

If I say `& "${DIR_FOR_BIN}/bin/erl.exe -s erlang halt`, no dice,. hangs, as if it didn't get or interept the arguments, but if I do ... 

```
$cmdArgList = @(
	"-init_debug",
	"-s","erlang", "halt"
)

Write-Output "DEBUG => Run erl.exe with -init_debug -s erlang halt"
& "${DIR_FOR_BIN}/bin/erl.exe" $cmdArgList | Write-Output
```

Voila, it works. You can see here : https://github.com/starbelly/test-setup-elixir/actions/runs/5008806369/jobs/8977406748

erl reports the version, then starts up again with init debug, then halts as expected. 

This only solves the problem of `erl` itself ending up in this state, but I'd hope this is the same problem the elixir batch scripts are facing.

Why now? Did parameter parsing change with the new shell for windows? So many questions.

**Comment by josevalim** [comment] 2023-05-18 09:13
I was able to find what made Elixir CI fail: https://github.com/erlang/otp/issues/7261. I have no idea if that's the root cause here too.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-18 09:34
> Voila, it works. You can see here:

@starbelly, it still seems it's hanging, no? The version is never printed out. 🤔 

@josevalim, once that's available in Hex.pm (for e.g. elixir 1.14.4-otp-26) we can give it a shot at importing here. 👍

**Comment by starbelly** [comment] 2023-05-18 14:57
> > Voila, it works. You can see here:
> 
> @starbelly, it still seems it's hanging, no? The version is never printed out. 🤔 (**edit**: maybe it's just the link that's wrong (?))
> 


@paulo-ferraz-oliveira  It's noisy, here's another run https://github.com/starbelly/test-setup-elixir/actions/runs/5015176404/jobs/8990379441 

I hope @josevalim's fix is related. But yeah, prior erl would just hang if given multiple arguments, almost as if it got one argument it didn't understand and disregarded. 

In the CI run above, it's working, using the powershell array construct for passing arguments. Presumably a whole lot of escaping might be happening? 

Elixir is not working, because I'm not sure how to do that via a batch script.  

<img width="896" alt="Screenshot 2023-05-18 at 9 57 26 AM" src="https://github.com/erlef/setup-beam/assets/39971740/7c51c851-da25-40b2-914b-f3df8bdf9277">

**Comment by mkuratczyk** [comment] 2023-05-23 08:02
Elixir 1.14.5 solves the problem for me. Thank you!

![Screenshot 2023-05-23 at 09 53 34](https://github.com/erlef/setup-beam/assets/9566114/8a2f6418-a4ba-4ab4-beee-5de2577fab16)

I'm happy to close this issue but I'll leave it open in case there is more to do here

**Comment by josevalim** [comment] 2023-05-23 08:25
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-23 09:34
@mkuratczyk, that's good news. No need to close the issue, it's already linked to a pull request that should get merged soonish. Thanks.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-23 09:56
Hm... the first part (reporting the version) passes, but the Mix tests (that are passing in all but the new test scenarios) hang: https://github.com/erlef/setup-beam/actions/runs/5055776670/jobs/9072419528?pr=191#step:11:23, so I won't be merging the pull request yet.

**Comment by josevalim** [comment] 2023-05-23 11:46
The other issue seems to be related to this: https://github.com/elixir-lang/elixir/issues/12589

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-23 20:59
@dumbbell, yeah, according to the latest CI results, it's hanging with a call to mix, it seems. I haven't dug further, at the moment.

**Comment by josevalim** [comment] 2023-05-24 10:58
The same issue that we had in Elixir was also happening in rebar3. So if you have any rebar3 dependency, that would explain the hanging. A PR was sent to Rebar3 but there is also an issue on Erlang/OTP: https://github.com/erlang/rebar3/pull/2794

**Comment by dumbbell** [comment] 2023-08-28 10:54
Can this issue be reopened please? I tried again with Erlang/OTP 26 today and the install never completes.

Here is a build in progress at the time of this writing:
https://github.com/rabbitmq/khepri_mnesia_migration/actions/runs/5998555303/job/16267047505

setup-beam is installing Erlang/OTP 26 and Rebar for 36 minutes now. There is no messages in the GitHub Actions output yet, so I have no idea of the progress.

How can I help with this?

**Comment by josevalim** [comment] 2023-08-28 10:57
I don't have power to reopen, but can you please confirm you are at least on 26.0.2 and at least Rebar 3.22.0?

**Comment by dumbbell** [comment] 2023-08-28 11:36
> at least Rebar 3.22.0?

Indeed, that was the problem! The version was still pinned to 3.20.0. With 3.22.1, the setup went fine. Sorry, I misunderstood that in the previous messages.

Thank you @josevalim and @paulo-ferraz-oliveira! This issue can be closed again.

**Closed** 2023-08-28 11:44 UTC
Labels: help wanted
