### ISSUE TITLE
Erlang 25.3.2 installation on ubuntu-latest errors

### ISSUE THREAD

**Issue by sevenseacat** [erlef/setup-beam#199] opened 2023-05-06 17:40 UTC
(I tried to check out the repo and play with the code locally, but I'm on a Mac, so.... it didn't work too well)

25.3.2 is the latest published version of Erlang afaik, and I can see it listed in the builds file for Erlang here - https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt

So in my app, I updated my .tool-versions file to use it and pushed, but it errored - somewhere after successfully reading the version from the file and converting it to an OTP version, it turns into undefined - https://github.com/sevenseacat/advent_of_code/actions/runs/4902607975/jobs/8754814411#step:3:15

I also tried cloning the `setup-beam-example` app and changed the version in .tool-versions to see if it would work, but it doesn't (it gives the same error, the version is parsed as undefined) - https://github.com/sevenseacat/setup-beam-example/actions/runs/4902817864/jobs/8754887026#step:3:18

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-06 21:57
[Our tests](https://github.com/erlef/setup-beam/actions/runs/4879756332/jobs/8756451192#step:4:9) for 25 are reporting **latest** (calculated) as 25.3.1. That's odd.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-06 22:33
This seems to be picking up 25.3.2 Ok now. Mind you the current origin for the action is https://builds.hex.pm, not https://repo.hex.pm. I'm not sure if there's caching involved, for example.

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-06 23:46
I'm tentatively closing this as "fixed". Feel free to re-open if the issue is still present. @ericmj's input would still be valuable here, though.

**Closed by paulo-ferraz-oliveira** 2023-05-06 23:46 UTC

**Comment by sevenseacat** [comment] 2023-05-07 06:14
I'm still seeing it being an issue - not seeing where 25.3.2 is being picked up in the current tests.

And yeah 25.3.2 is a pretty new version of Erlang, so I thought there might be some caching of the builds file involved?

**Comment by ericmj** [comment] 2023-05-07 13:54
We weren't purging the builds.hex.pm cache so some POP nodes had the older `builds.txt` file cache. This has been fixed now.

<img width="1547" alt="Screenshot 2023-05-07 at 15 30 13" src="https://user-images.githubusercontent.com/316890/236681735-37284850-e342-4de1-b2bc-63575a36a43c.png">

**Comment by paulo-ferraz-oliveira** [comment] 2023-05-07 14:00
Tests: https://github.com/erlef/setup-beam/actions/runs/4879756332/jobs/8756722600#step:3:13

If you look closely, input is `25`, and we're picking up/translating this to `25.3.2`.

As per what @ericmj explained this was Hex.pm -related and not action -related.

Do you still prefer we re-open to discuss something else?

**Comment by sevenseacat** [comment] 2023-05-08 00:45
Nope it's all good, thanks for looking into the issue so quickly! :)
